2024-03-21 16:34:38,349 - root - INFO - Cleaning start, Batch_id:2021

2024-03-21 16:35:25,809 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:47.

2024-03-21 16:37:28,355 - root - INFO - Cleaning start, Batch_id:2021

2024-03-21 16:37:34,806 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:06.

2024-03-21 16:55:44,340 - root - INFO - Cleaning start, Batch_id:2021

2024-03-21 16:55:53,058 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:09.

2024-03-21 16:57:05,486 - root - INFO - Cleaning start, Batch_id:2021

2024-03-21 16:57:11,973 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:06.

2024-03-21 16:59:00,161 - root - INFO - Cleaning start, Batch_id:2021

2024-03-21 16:59:06,493 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:06.

2024-03-21 17:04:42,651 - root - INFO - Cleaning start, Batch_id:2021

2024-03-21 17:04:49,352 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:07.

2024-03-21 17:47:45,936 - root - INFO - Cleaning start, Batch_id:2021

2024-03-21 17:47:52,271 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:06.

2024-03-22 18:21:27,953 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:21:28,283 - root - INFO - Caught an unexpected exception: 'list' object has no attribute 'split',

2024-03-22 18:22:29,602 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:22:29,947 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:23:30,143 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:23:30,509 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:25:59,976 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:26:00,373 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:27:00,119 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:27:00,523 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:27:17,797 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:27:18,191 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:28:48,733 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:28:49,133 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:29:49,375 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:29:49,761 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:31:40,122 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:31:40,491 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:34:27,602 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:34:27,966 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:35:47,835 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:35:48,266 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:39:51,416 - root - INFO - Cleaning start, Batch_id:2021

2024-03-22 18:39:51,861 - root - INFO - Caught an unexpected exception: save_progress() missing 1 required positional argument: 'year',

2024-03-27 21:06:00,876 - root - INFO - Cleaning start, Batch_id:2021

2024-03-27 21:06:00,887 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:00:00.

2024-03-27 21:06:19,132 - root - INFO - Cleaning start, Batch_id:2021

2024-03-27 21:08:52,961 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:02:34.

2024-04-03 18:30:13,373 - root - INFO - Cleaning start, Batch_id:2021

2024-04-03 18:36:05,041 - root - INFO - 50 Batch Completed. Processing:100%.[ 00:05:52/00:05:52, 142.05it/s ]

2024-04-03 18:36:05,043 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:05:52.

2024-04-03 20:13:16,540 - root - INFO - Cleaning start, Batch_id:2021

2024-04-03 20:13:21,165 - root - INFO - Caught an unexpected exception: "['Ô­ÎÄ'] not in index",

2024-04-03 20:15:02,733 - root - INFO - Cleaning start, Batch_id:2021

2024-04-03 20:15:13,401 - root - INFO - Caught an unexpected exception: expected string or bytes-like object, got 'float',

2024-04-03 20:16:33,202 - root - INFO - Cleaning start, Batch_id:2021

2024-04-03 20:18:47,276 - root - INFO - Cleaning start, Batch_id:2021

2024-04-03 20:19:40,775 - root - INFO - Network Error Occured: mongo.fqyai.cn:27017: [Errno 11001] getaddrinfo failed (configured timeouts: connectTimeoutMS: 20000.0ms),

2024-04-03 20:21:44,859 - root - INFO - Cleaning start, Batch_id:2021

2024-04-03 20:25:50,079 - root - INFO - 50 Batch Completed. Processing:100%.[ 00:04:05/00:04:05, 204.08it/s ]

2024-04-03 20:25:50,080 - root - INFO - WS_2021 CLeaning Completed. Time-Consuming: 00:04:05.

